pipeline {
     agent any
     stages {
         stage('build') {
              when {
                  branch 'master'             
              }
              steps {
                 echo "Working on master branch"
              }
         }
     }
}